### ISSUE TITLE
New fork: @halkeye/hubot-postgres-brain

### ISSUE THREAD

**Issue by halkeye** [changhaitravis/hubot-postgres-brain#3]
I don't know if your interested in me merging it back at all, I've released it as @halkeye/hubot-postgres-brain

https://github.com/halkeye/hubot-postgres-brain

I removed coffeescript, upgraded to latest postgres, and changed the url parsing

I plan to add more testing, and see if i can't even detect changes to the brain and only save when changes happen.

**Comment by changhaitravis** [comment]
When you feel it is ready for primetime, go ahead and file a pull request and I'll look over the changes. I'm not tied to coffeescript or anything, and test coverage is more than welcome. I'll publish to npmjs after it is merged.
